# Generated by Django 3.1.7 on 2021-03-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=40, verbose_name='Currency Code')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Amount',
                'verbose_name_plural': 'Amounts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('plan_id', models.CharField(blank=True, max_length=128, verbose_name='Billing Plan ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.CharField(max_length=127, verbose_name='Description')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('quantity_supported', models.BooleanField(default=False, verbose_name='Quantity Supported')),
                ('create_time', models.DateTimeField(null=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(null=True, verbose_name='Update Time')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='Links')),
            ],
            options={
                'verbose_name': 'Billing Plan',
                'verbose_name_plural': 'Billing Plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_unit', models.CharField(choices=[('MONTH', 'Month')], max_length=20, verbose_name='Interval Unit')),
                ('interval_count', models.PositiveIntegerField(default=1, verbose_name='Interval Count')),
            ],
            options={
                'verbose_name': 'Frequency',
                'verbose_name_plural': 'Frequencies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical Goods'), ('DIGITAL', 'Digital Goods'), ('SERVICE', 'A Service')], max_length=24, verbose_name='Type')),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software')], max_length=60, verbose_name='Category')),
                ('image_url', models.URLField(blank=True, verbose_name='Image URL')),
                ('home_url', models.URLField(blank=True, verbose_name='Home URL')),
                ('create_time', models.DateTimeField(verbose_name='Create Time')),
                ('update_time', models.DateTimeField(verbose_name='Update Time')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='Links')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PricingScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_schemes', to='paypal.amount', verbose_name='Fixed Price')),
            ],
            options={
                'verbose_name': 'Pricing Scheme',
                'verbose_name_plural': 'Pricing Schemes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_bill_outstanding', models.BooleanField(default=True, verbose_name='Auto Bill Outstanding')),
                ('setup_fee_failure_action', models.CharField(choices=[('CONTINUE', 'Continue')], max_length=30, verbose_name='Setup Fee Failure Action')),
                ('payment_failure_threshold', models.PositiveIntegerField(default=0, verbose_name='Payment Failure Threshold')),
                ('billing_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preferences', to='paypal.billingplan', verbose_name='Billing Plan')),
                ('setup_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preferences', to='paypal.amount', verbose_name='Setup Fee')),
            ],
            options={
                'verbose_name': 'Payment Preference',
                'verbose_name_plural': 'Payment Preferences',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='billingplan',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='paypal.product', verbose_name='Product'),
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure_type', models.CharField(choices=[('TRIAL', 'Trial'), ('REGULAR', 'Regular')], max_length=20, verbose_name='Tenure Type')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sequence')),
                ('total_cycles', models.PositiveIntegerField(default=0, verbose_name='Total Cycles')),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='paypal.billingplan', verbose_name='Billing Plan')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='paypal.frequency', verbose_name='Frequency')),
                ('pricing_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='paypal.pricingscheme', verbose_name='Pricing Scheme')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-id'],
            },
        ),
    ]
