# Generated by Django 3.1.7 on 2021-03-14 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subscription_valid_till', models.DateTimeField(blank=True, null=True, verbose_name='Subscription Valid Till')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Paypal Profile',
                'verbose_name_plural': 'Paypal Profiles',
                'ordering': ['-id'],
            },
        ),
    ]
