# Generated by Django 3.1.7 on 2021-03-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paypal', '0002_paypalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=160, verbose_name='Subscription Id')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], max_length=40, verbose_name='Status')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('billing_info', models.JSONField(blank=True, default=dict, verbose_name='Billing Info')),
                ('create_time', models.DateTimeField(verbose_name='Create Time')),
                ('update_time', models.DateTimeField(verbose_name='Update Time')),
                ('links', models.JSONField(default=list, verbose_name='Links')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='paypal.billingplan', verbose_name='Plan')),
                ('shipping_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paypal.amount', verbose_name='Shipping Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=dict, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paypal.subscription', verbose_name='Subscription')),
            ],
        ),
    ]
